### ISSUE TITLE
Doxygen runs and exit without errors

### ISSUE THREAD

**Issue by fbramato** [dokempf/doxygen-install#4]
Hi,
thanks for this useful action.

In my workflow, Doxygen installed with this action has a strange behaviour:

Prints only this and returns exit code 1

> Doxygen version used: 1.10.0 (ebc57c6dd303a980bd19dd74b8b61c8f3f5180ca)
> Exiting...

No warnings, no errors. just this. Running the same Doxyfile on my computer both from Windows and WSL, it works.

Would appreciate any suggestion to point me in the right direction.

Thanks

**Comment by dokempf** [comment]
Looking at your output, it seems like the Doxygen executable was found just fine - how would it report the version including a build hash otherwise. That means basically that this action has done all of its job - install the Doxygen executable and make it discoverable on the PATH. That being said, I doubt that it is this action's fault.

Maybe trying setting the Doxygen version to exactly what you are using and also make sure that the Doxyfile is exactly where you think it should be.

**Comment by fbramato** [comment]
hi, thanks for your response.
found the error: is casued by not having the destination folder created. 

See https://github.com/doxygen/doxygen/issues/10866#issuecomment-2114500725 

Thanks
